name: 'ci'
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    name: earthly +hello
    permissions:
      contents: read
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EarthBuild/actions-setup@234ca5f9d838c6ab50ccf331f5c0da74e5626b6c
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
          prerelease: true
      - run: earthly +hello
